---
title: "Zen-R2-1"
author: "Meher"
date: "2024-04-11"
output: html_document
---

stock.prices=c(23,27,23,21,34) stock.prices

```{r}
stock.prices=c(23,27,23,21,34)
stock.prices
```

```{r}
num_vec=c(1,2,3,4,5,6,7,8,9,10)
sum(num_vec)
```

```{r}
a=c("a","b","c","d","e")
print(a[[2]])
print(a[[4]])
```

```{r}
?mtcars
```

```{r}

```

```{r}
data(mtcars)
```

```{r}
head(mtcars,6)
```

```{r}
x=mtcars$mpg
y=mtcars$hp
plot(x,y,xlab='mpg',ylab='hp',main='Distribution of mpg & hp')
```

```{r}
my_list=list(c(1,2,3),c("a","b","c"),matrix(1:4,nrow=2,ncol=2))
```

```{r}
my_list1=append(my_list,c(TRUE,FALSE))
my_list1
```

```{r}
words=c("R","is","fun")
words
```

```{r}

```

```{r}
my_fun=function(a){
  cat(a,sep=" ")
}
my_fun(words)
```

```{r}
my_fun1=function(a){
  a[[3]]="awesome"
  cat(a,sep=" ")
}
my_fun1(words)
```

```{r}
```

```{r}
v_num=c(1,2,3)
char_v1=as.character(v_num)
char_v1
```

```{r}
v_char=c("low","medium","high")
b=factor(v_char)
b
```

```{r}
ind=as.integer(b)
ind
```

```{r}
colors = c("red", "blue", "green", "blue", "red", "green", "green", "red")

f_colors=factor(colors,levels=c("green","blue","red"))
f_colors
```

```{r}
my_list<-list(name="Alice",age=30,hobbies=c("Cycling","Art","Music"))
my_df<-data.frame(Name=c("Alice","Bob"),Age=c(25,30))

print(my_list[3])
cbind(my_df,Occupation="Doctor","Engineer")
```
